/**
 * Curated replacement data for the demo catalogue, in the exact _id order
 * `node scripts/reseedCatalogue.js --list` prints — the seed script zips this
 * array against that order positionally, so an entry's index is its identity,
 * not its title. Every title is a real, released film or series; ratings are
 * expressed on the site's 0–5 star scale (real IMDb/10 and RT/100 divided
 * down), and descriptions are written from scratch rather than copied from
 * any official synopsis.
 */

const GENRES = [
    'action', 'comedy', 'drama', 'horror', 'science fiction', 'fantasy', 'romance',
    'thriller', 'mystery', 'documentary', 'adventure', 'crime', 'musical', 'western',
    'animation', 'war',
];

const r5 = (x10) => Math.round((x10 / 2) * 10) / 10;
const rt5 = (pct) => Math.round((pct / 20) * 10) / 10;

const MOVIES = [
    { title: 'Deadpool 2', genres: ['action', 'comedy'], country: 'United States', language: 'English', age_rating: 'R', imdb: r5(7.7), rt: rt5(84), year: '2018', duration: 119, director: 'David Leitch', actors: ['Ryan Reynolds', 'Josh Brolin', 'Morena Baccarin'], description: 'A wisecracking mercenary assembles a ragtag team to protect a troubled young mutant from a time-travelling soldier.' },
    { title: 'The Dark Knight', genres: ['action', 'crime'], country: 'United States', language: 'English', age_rating: 'PG-13', imdb: r5(9.0), rt: rt5(94), year: '2008', duration: 152, director: 'Christopher Nolan', actors: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'], description: 'Batman raises the stakes in his war on crime as an anarchic mastermind known as the Joker brings chaos to Gotham City.' },
    { title: 'Inception', genres: ['science fiction', 'thriller'], country: 'United States', language: 'English', age_rating: 'PG-13', imdb: r5(8.8), rt: rt5(87), year: '2010', duration: 148, director: 'Christopher Nolan', actors: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'], description: 'A thief who enters people’s dreams to steal secrets is offered a chance at redemption: planting an idea instead of stealing one.' },
    { title: 'The Batman', genres: ['action', 'crime'], country: 'United States', language: 'English', age_rating: 'PG-13', imdb: r5(7.8), rt: rt5(85), year: '2022', duration: 176, director: 'Matt Reeves', actors: ['Robert Pattinson', 'Zoë Kravitz', 'Paul Dano'], description: 'A younger, more unstable Batman uncovers corruption in Gotham while hunting a serial killer who targets the city’s elite.' },
    { title: 'Interstellar', genres: ['science fiction', 'drama'], country: 'United States', language: 'English', age_rating: 'PG-13', imdb: r5(8.7), rt: rt5(73), year: '2014', duration: 169, director: 'Christopher Nolan', actors: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'], description: 'With Earth dying, a pilot leads a crew through a wormhole in search of a new home for humanity, racing against time itself.' },
    { title: 'The Matrix', genres: ['science fiction', 'action'], country: 'United States', language: 'English', age_rating: 'R', imdb: r5(8.7), rt: rt5(83), year: '1999', duration: 136, director: 'Lana Wachowski', actors: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'], description: 'A computer programmer discovers the world he knows is a simulation, and joins a rebellion against the machines that built it.' },
    { title: 'Pulp Fiction', genres: ['crime', 'drama'], country: 'United States', language: 'English', age_rating: 'R', imdb: r5(8.9), rt: rt5(92), year: '1994', duration: 154, director: 'Quentin Tarantino', actors: ['John Travolta', 'Samuel L. Jackson', 'Uma Thurman'], description: 'The lives of two hitmen, a boxer and a gangster’s wife intertwine in four tales of violence and redemption across Los Angeles.' },
    { title: 'Fight Club', genres: ['drama', 'thriller'], country: 'United States', language: 'English', age_rating: 'R', imdb: r5(8.8), rt: rt5(79), year: '1999', duration: 139, director: 'David Fincher', actors: ['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'], description: 'An insomniac office worker and a soap salesman build an underground fight club that spirals into something far more dangerous.' },
    { title: 'Public Enemies', genres: ['crime', 'drama'], country: 'United States', language: 'English', age_rating: 'R', imdb: r5(7.0), rt: rt5(70), year: '2009', duration: 140, director: 'Michael Mann', actors: ['Johnny Depp', 'Christian Bale', 'Marion Cotillard'], description: 'The FBI’s pursuit of bank robber John Dillinger during a crime wave that gripped Depression-era America.' },
    { title: 'American Murderer', genres: ['crime', 'drama'], country: 'United States', language: 'English', age_rating: 'R', imdb: r5(5.8), rt: rt5(45), year: '2022', duration: 99, director: 'Matthew Gentile', actors: ['Tom Pelphrey', 'Ryan Phillippe', 'Idina Menzel'], description: 'The rise and unravelling of a con man whose fraud schemes put him on the FBI’s most wanted list.' },
    { title: 'The Army of Crime', genres: ['war', 'drama'], country: 'France', language: 'French', age_rating: 'R', imdb: r5(6.9), rt: rt5(64), year: '2009', duration: 139, director: 'Robert Guédiguian', actors: ['Simon Abkarian', 'Virginie Ledoyen', 'Robinson Stevenin'], description: 'A group of immigrant resistance fighters wage a guerrilla campaign against the Nazi occupation of Paris.' },
    { title: 'The Nun', genres: ['horror', 'mystery'], country: 'United States', language: 'English', age_rating: 'R', imdb: r5(5.3), rt: rt5(26), year: '2018', duration: 96, director: 'Corin Hardy', actors: ['Demi Moore', 'Taissa Farmiga', 'Jonas Bloquet'], description: 'A priest and a novice investigate the death of a nun at a cloistered abbey in Romania and uncover a demonic presence.' },
    { title: 'Parasite', genres: ['thriller', 'drama'], country: 'South Korea', language: 'Korean', age_rating: 'R', imdb: r5(8.5), rt: rt5(99), year: '2019', duration: 132, director: 'Bong Joon-ho', actors: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'], description: 'A poor family schemes their way into the household of a wealthy one, setting off a chain of events no one sees coming.' },
    { title: 'Whiplash', genres: ['drama', 'musical'], country: 'United States', language: 'English', age_rating: 'R', imdb: r5(8.5), rt: rt5(94), year: '2014', duration: 106, director: 'Damien Chazelle', actors: ['Miles Teller', 'J.K. Simmons'], description: 'A driven young drummer clashes with an abusive instructor determined to push him past his limits.' },
    { title: 'La La Land', genres: ['musical', 'romance'], country: 'United States', language: 'English', age_rating: 'PG-13', imdb: r5(8.0), rt: rt5(91), year: '2016', duration: 128, director: 'Damien Chazelle', actors: ['Ryan Gosling', 'Emma Stone'], description: 'A jazz pianist and an aspiring actress fall in love while chasing their dreams in Los Angeles.' },
    { title: 'Mad Max: Fury Road', genres: ['action', 'adventure'], country: 'Australia', language: 'English', age_rating: 'R', imdb: r5(8.1), rt: rt5(97), year: '2015', duration: 120, director: 'George Miller', actors: ['Tom Hardy', 'Charlize Theron'], description: 'In a scorched wasteland, a drifter joins a rebel warrior fleeing a tyrant across the desert in a war rig.' },
    { title: 'The Grand Budapest Hotel', genres: ['comedy', 'adventure'], country: 'Germany', language: 'English', age_rating: 'R', imdb: r5(8.1), rt: rt5(92), year: '2014', duration: 99, director: 'Wes Anderson', actors: ['Ralph Fiennes', 'Tony Revolori'], description: 'A legendary hotel concierge and his apprentice get caught up in a theft, a murder and a prison break between the world wars.' },
    { title: 'Get Out', genres: ['horror', 'mystery'], country: 'United States', language: 'English', age_rating: 'R', imdb: r5(7.7), rt: rt5(98), year: '2017', duration: 104, director: 'Jordan Peele', actors: ['Daniel Kaluuya', 'Allison Williams'], description: 'A young man’s visit to his girlfriend’s family estate reveals a horrifying secret beneath their liberal hospitality.' },
    { title: 'Knives Out', genres: ['mystery', 'comedy'], country: 'United States', language: 'English', age_rating: 'PG-13', imdb: r5(7.9), rt: rt5(97), year: '2019', duration: 130, director: 'Rian Johnson', actors: ['Daniel Craig', 'Ana de Armas', 'Chris Evans'], description: 'A detective investigates the death of a wealthy crime novelist, and every member of his dysfunctional family is a suspect.' },
    { title: 'Johnny English Strikes Again', genres: ['action', 'comedy'], country: 'United Kingdom', language: 'English', age_rating: 'PG', imdb: r5(6.1), rt: rt5(45), year: '2018', duration: 89, director: 'David Kerr', actors: ['Rowan Atkinson', 'Olga Kurylenko'], description: 'Britain’s most accident-prone secret agent is called out of retirement to unmask a cyberattack mastermind.' },
    { title: 'Dune', genres: ['science fiction', 'adventure'], country: 'United States', language: 'English', age_rating: 'PG-13', imdb: r5(8.0), rt: rt5(83), year: '2021', duration: 155, director: 'Denis Villeneuve', actors: ['Timothe Chalamet', 'Rebecca Ferguson', 'Zendaya'], description: 'The heir of a noble house is thrust into a war for control of the galaxy’s most valuable and dangerous desert planet.' },
    { title: 'Oppenheimer', genres: ['drama', 'war'], country: 'United States', language: 'English', age_rating: 'R', imdb: r5(8.4), rt: rt5(93), year: '2023', duration: 180, director: 'Christopher Nolan', actors: ['Cillian Murphy', 'Emily Blunt', 'Robert Downey Jr.'], description: 'The physicist who led the effort to build the atomic bomb grapples with the consequences of what he unleashed.' },
    { title: 'The Social Network', genres: ['drama'], country: 'United States', language: 'English', age_rating: 'PG-13', imdb: r5(7.7), rt: rt5(96), year: '2010', duration: 120, director: 'David Fincher', actors: ['Jesse Eisenberg', 'Andrew Garfield'], description: 'The founding of Facebook spirals into lawsuits and broken friendships as ambition outpaces loyalty.' },
    { title: 'Gladiator', genres: ['action', 'drama'], country: 'United States', language: 'English', age_rating: 'R', imdb: r5(8.5), rt: rt5(80), year: '2000', duration: 155, director: 'Ridley Scott', actors: ['Russell Crowe', 'Joaquin Phoenix'], description: 'A betrayed Roman general is sold into slavery and rises through the gladiator ranks to seek revenge on the empire.' },
    { title: 'The Godfather', genres: ['crime', 'drama'], country: 'United States', language: 'English', age_rating: 'R', imdb: r5(9.2), rt: rt5(97), year: '1972', duration: 175, director: 'Francis Ford Coppola', actors: ['Marlon Brando', 'Al Pacino'], description: 'The aging patriarch of an organised crime dynasty transfers control of his empire to his reluctant youngest son.' },
    { title: 'Forrest Gump', genres: ['drama', 'romance'], country: 'United States', language: 'English', age_rating: 'PG-13', imdb: r5(8.8), rt: rt5(71), year: '1994', duration: 142, director: 'Robert Zemeckis', actors: ['Tom Hanks', 'Robin Wright'], description: 'A slow-witted but kind-hearted man from Alabama witnesses and unwittingly influences several defining moments of the 20th century.' },
    { title: 'The Shawshank Redemption', genres: ['drama'], country: 'United States', language: 'English', age_rating: 'R', imdb: r5(9.3), rt: rt5(91), year: '1994', duration: 142, director: 'Frank Darabont', actors: ['Tim Robbins', 'Morgan Freeman'], description: 'A banker wrongly convicted of murder forms an unlikely friendship with a fellow inmate over two decades in prison.' },
    { title: 'Coco', genres: ['animation', 'musical'], country: 'United States', language: 'English', age_rating: 'PG', imdb: r5(8.4), rt: rt5(97), year: '2017', duration: 105, director: 'Lee Unkrich', actors: ['Anthony Gonzalez', 'Gael Garcia Bernal'], description: 'A boy who dreams of becoming a musician is transported to the Land of the Dead, where he uncovers his family’s hidden history.' },
    { title: 'Spirited Away', genres: ['animation', 'fantasy'], country: 'Japan', language: 'Japanese', age_rating: 'PG', imdb: r5(8.6), rt: rt5(96), year: '2001', duration: 125, director: 'Hayao Miyazaki', actors: ['Rumi Hiiragi', 'Miyu Irino'], description: 'A young girl wandering into a world of spirits must work in a bathhouse to free her parents from a curse.' },
    { title: 'Toy Story', genres: ['animation', 'adventure'], country: 'United States', language: 'English', age_rating: 'G', imdb: r5(8.3), rt: rt5(100), year: '1995', duration: 81, director: 'John Lasseter', actors: ['Tom Hanks', 'Tim Allen'], description: 'A cowboy doll’s place as a boy’s favourite toy is threatened by the arrival of a flashy new space ranger.' },
    { title: 'Jurassic Park', genres: ['adventure', 'science fiction'], country: 'United States', language: 'English', age_rating: 'PG-13', imdb: r5(8.2), rt: rt5(91), year: '1993', duration: 127, director: 'Steven Spielberg', actors: ['Sam Neill', 'Laura Dern', 'Jeff Goldblum'], description: 'A theme park of cloned dinosaurs descends into chaos when its security systems fail during a storm.' },
    { title: 'Titanic', genres: ['romance', 'drama'], country: 'United States', language: 'English', age_rating: 'PG-13', imdb: r5(7.9), rt: rt5(88), year: '1997', duration: 195, director: 'James Cameron', actors: ['Leonardo DiCaprio', 'Kate Winslet'], description: 'A penniless artist and a young woman engaged to be married fall in love aboard the doomed ocean liner.' },
    { title: 'Avengers: Endgame', genres: ['action', 'science fiction'], country: 'United States', language: 'English', age_rating: 'PG-13', imdb: r5(8.4), rt: rt5(94), year: '2019', duration: 181, director: 'Anthony Russo', actors: ['Robert Downey Jr.', 'Chris Evans', 'Scarlett Johansson'], description: 'The surviving Avengers assemble one last time to undo the devastation wrought by a galactic tyrant.' },
    { title: 'Spider-Man: Into the Spider-Verse', genres: ['animation', 'action'], country: 'United States', language: 'English', age_rating: 'PG', imdb: r5(8.4), rt: rt5(97), year: '2018', duration: 117, director: 'Bob Persichetti', actors: ['Shameik Moore', 'Hailee Steinfeld'], description: 'A teenager from Brooklyn discovers he is one of many Spider-People pulled together to save the multiverse.' },
    { title: 'Joker', genres: ['drama', 'thriller'], country: 'United States', language: 'English', age_rating: 'R', imdb: r5(8.4), rt: rt5(68), year: '2019', duration: 122, director: 'Todd Phillips', actors: ['Joaquin Phoenix', 'Robert De Niro'], description: 'A failed clown and aspiring comedian’s descent into madness gives rise to an icon of chaos in Gotham City.' },
    { title: '1917', genres: ['war', 'drama'], country: 'United Kingdom', language: 'English', age_rating: 'R', imdb: r5(8.2), rt: rt5(89), year: '2019', duration: 119, director: 'Sam Mendes', actors: ['George MacKay', 'Dean-Charles Chapman'], description: 'Two young soldiers race across enemy territory to deliver a message that could save sixteen hundred men.' },
    { title: 'No Country for Old Men', genres: ['crime', 'thriller'], country: 'United States', language: 'English', age_rating: 'R', imdb: r5(8.2), rt: rt5(93), year: '2007', duration: 122, director: 'Joel Coen', actors: ['Tommy Lee Jones', 'Javier Bardem', 'Josh Brolin'], description: 'A hunter who stumbles on a drug deal gone wrong finds himself the target of a remorseless killer.' },
    { title: 'The Departed', genres: ['crime', 'thriller'], country: 'United States', language: 'English', age_rating: 'R', imdb: r5(8.5), rt: rt5(91), year: '2006', duration: 151, director: 'Martin Scorsese', actors: ['Leonardo DiCaprio', 'Matt Damon', 'Jack Nicholson'], description: 'An undercover cop and a mob informant embedded in the police force race to expose each other before it’s too late.' },
    { title: 'Django Unchained', genres: ['western', 'drama'], country: 'United States', language: 'English', age_rating: 'R', imdb: r5(8.4), rt: rt5(87), year: '2012', duration: 165, director: 'Quentin Tarantino', actors: ['Jamie Foxx', 'Christoph Waltz', 'Leonardo DiCaprio'], description: 'A freed slave partners with a bounty hunter to track down the plantation owner holding his wife captive.' },
    { title: 'Once Upon a Time in Hollywood', genres: ['drama', 'comedy'], country: 'United States', language: 'English', age_rating: 'R', imdb: r5(7.6), rt: rt5(85), year: '2019', duration: 161, director: 'Quentin Tarantino', actors: ['Leonardo DiCaprio', 'Brad Pitt', 'Margot Robbie'], description: 'A fading TV star and his stunt double navigate a changing Hollywood on the eve of the Manson murders.' },
    { title: 'A Quiet Place', genres: ['horror', 'science fiction'], country: 'United States', language: 'English', age_rating: 'PG-13', imdb: r5(7.5), rt: rt5(96), year: '2018', duration: 90, director: 'John Krasinski', actors: ['Emily Blunt', 'John Krasinski'], description: 'A family must live in near-total silence to hide from creatures that hunt anything that makes a sound.' },
    { title: 'Hereditary', genres: ['horror', 'drama'], country: 'United States', language: 'English', age_rating: 'R', imdb: r5(7.3), rt: rt5(89), year: '2018', duration: 127, director: 'Ari Aster', actors: ['Toni Collette', 'Alex Wolff'], description: 'A family unravels dark secrets after the death of their secretive grandmother releases something ancient and cruel.' },
    { title: 'The Conjuring', genres: ['horror', 'mystery'], country: 'United States', language: 'English', age_rating: 'R', imdb: r5(7.5), rt: rt5(86), year: '2013', duration: 112, director: 'James Wan', actors: ['Patrick Wilson', 'Vera Farmiga'], description: 'Paranormal investigators are called to help a family terrorised by a dark presence in their farmhouse.' },
];

const SERIES = [
    { title: 'Halo', genres: ['science fiction', 'action'], country: 'United States', language: 'English', age_rating: 'TV-MA', imdb: r5(7.0), rt: rt5(56), year: '2022', director: 'Steven Kane', actors: ['Pablo Schreiber', 'Yerin Ha'], description: 'A supersoldier on the front lines of a war with an alien empire begins to question the truth behind his own creation.' },
    { title: 'Farzi', genres: ['crime', 'thriller'], country: 'India', language: 'Hindi', age_rating: 'TV-MA', imdb: r5(8.3), rt: rt5(80), year: '2023', director: 'Raj Nidimoru', actors: ['Shahid Kapoor', 'Vijay Sethupathi'], description: 'A struggling artist’s talent for forgery pulls him into a counterfeit currency operation that spirals out of control.' },
    { title: 'Breaking Bad', genres: ['crime', 'drama'], country: 'United States', language: 'English', age_rating: 'TV-MA', imdb: r5(9.5), rt: rt5(96), year: '2008', director: 'Vince Gilligan', actors: ['Bryan Cranston', 'Aaron Paul'], description: 'A high school chemistry teacher turns to manufacturing methamphetamine after a terminal diagnosis, with irreversible consequences.' },
    { title: 'Money Heist', genres: ['crime', 'thriller'], country: 'Spain', language: 'Spanish', age_rating: 'TV-MA', imdb: r5(8.2), rt: rt5(91), year: '2017', director: 'Álex Pina', actors: ['Ursula Corbero', 'Alvaro Morte'], description: 'A mastermind recruits eight thieves to pull off the biggest heist in history at Spain’s Royal Mint.' },
    { title: 'Vikings: Valhalla', genres: ['action', 'drama'], country: 'Ireland', language: 'English', age_rating: 'TV-MA', imdb: r5(7.6), rt: rt5(82), year: '2022', director: 'Jeb Stuart', actors: ['Sam Corlett', 'Frida Gustavsson'], description: 'A century after the events of Vikings, a new generation of Norse legends reshapes the fate of England and Scandinavia.' },
    { title: 'One Piece', genres: ['adventure', 'fantasy'], country: 'United States', language: 'English', age_rating: 'TV-14', imdb: r5(8.1), rt: rt5(83), year: '2023', director: 'Matt Owens', actors: ['Iñaki Godoy', 'Emily Rudd'], description: 'A young pirate with an elastic body sets sail with a ragtag crew in search of the legendary treasure known as One Piece.' },
    { title: 'Better Call Saul', genres: ['crime', 'drama'], country: 'United States', language: 'English', age_rating: 'TV-MA', imdb: r5(8.9), rt: rt5(97), year: '2015', director: 'Vince Gilligan', actors: ['Bob Odenkirk', 'Rhea Seehorn'], description: 'A small-time lawyer’s slow transformation into the morally flexible fixer he was always destined to become.' },
    { title: 'The Last of Us', genres: ['drama', 'horror'], country: 'United States', language: 'English', age_rating: 'TV-MA', imdb: r5(8.7), rt: rt5(96), year: '2023', director: 'Craig Mazin', actors: ['Pedro Pascal', 'Bella Ramsey'], description: 'A smuggler is hired to escort a teenage girl across a ravaged country after a fungal infection turns most of humanity feral.' },
    { title: 'Narcos', genres: ['crime', 'documentary'], country: 'United States', language: 'Spanish', age_rating: 'TV-MA', imdb: r5(8.8), rt: rt5(83), year: '2015', director: 'Chris Brancato', actors: ['Wagner Moura', 'Boyd Holbrook'], description: 'The rise of Colombian drug lord Pablo Escobar and the DEA agents dedicated to bringing his cartel down.' },
    { title: 'Chernobyl', genres: ['drama', 'documentary'], country: 'United Kingdom', language: 'English', age_rating: 'TV-MA', imdb: r5(9.4), rt: rt5(96), year: '2019', director: 'Johan Renck', actors: ['Jared Harris', 'Stellan Skarsgard'], description: 'The 1986 nuclear disaster and the scientists who risked everything to uncover the truth and contain the fallout.' },
    { title: 'Fargo', genres: ['crime', 'drama'], country: 'United States', language: 'English', age_rating: 'TV-MA', imdb: r5(8.9), rt: rt5(94), year: '2014', director: 'Noah Hawley', actors: ['Billy Bob Thornton', 'Martin Freeman'], description: 'A drifter’s arrival in a snowbound Minnesota town sets off a chain of murder that upends an insurance salesman’s life.' },
    { title: 'Friends', genres: ['comedy', 'romance'], country: 'United States', language: 'English', age_rating: 'TV-PG', imdb: r5(8.9), rt: rt5(78), year: '1994', director: 'Marta Kauffman', actors: ['Jennifer Aniston', 'Courteney Cox', 'Matthew Perry'], description: 'Six friends navigate careers, romance and each other’s company through their twenties and thirties in Manhattan.' },
    { title: 'Narcos: Mexico', genres: ['crime', 'documentary'], country: 'United States', language: 'Spanish', age_rating: 'TV-MA', imdb: r5(8.4), rt: rt5(92), year: '2018', director: 'Carlo Bernard', actors: ['Diego Luna', 'Michael Pena'], description: 'The origins of the Mexican drug trade and the DEA agent who first went toe-to-toe with the Guadalajara cartel.' },
    { title: 'True Detective', genres: ['crime', 'mystery'], country: 'United States', language: 'English', age_rating: 'TV-MA', imdb: r5(8.9), rt: rt5(87), year: '2014', director: 'Nic Pizzolatto', actors: ['Matthew McConaughey', 'Woody Harrelson'], description: 'Two Louisiana detectives are drawn back into a case they thought they closed seventeen years earlier.' },
    { title: 'Peaky Blinders', genres: ['crime', 'drama'], country: 'United Kingdom', language: 'English', age_rating: 'TV-MA', imdb: r5(8.8), rt: rt5(92), year: '2013', director: 'Steven Knight', actors: ['Cillian Murphy', 'Paul Anderson'], description: 'A Birmingham gangster family expands its criminal empire in the years following the First World War.' },
    { title: 'The Wire', genres: ['crime', 'drama'], country: 'United States', language: 'English', age_rating: 'TV-MA', imdb: r5(9.3), rt: rt5(94), year: '2002', director: 'David Simon', actors: ['Dominic West', 'Idris Elba'], description: 'Baltimore’s drug trade is examined from every angle, from street dealers to the police, politicians and press covering them.' },
    { title: 'Sherlock', genres: ['mystery', 'crime'], country: 'United Kingdom', language: 'English', age_rating: 'TV-14', imdb: r5(9.1), rt: rt5(78), year: '2010', director: 'Steven Moffat', actors: ['Benedict Cumberbatch', 'Martin Freeman'], description: 'A consulting detective and his army-doctor companion take on London’s strangest cases in the present day.' },
    { title: 'Black Mirror', genres: ['science fiction', 'thriller'], country: 'United Kingdom', language: 'English', age_rating: 'TV-MA', imdb: r5(8.7), rt: rt5(83), year: '2011', director: 'Charlie Brooker', actors: ['Bryce Dallas Howard', 'Jesse Plemons'], description: 'A standalone anthology exploring the unintended consequences of technology on a near-future society.' },
    { title: 'The Boys', genres: ['action', 'crime'], country: 'United States', language: 'English', age_rating: 'TV-MA', imdb: r5(8.7), rt: rt5(93), year: '2019', director: 'Eric Kripke', actors: ['Karl Urban', 'Jack Quaid', 'Antony Starr'], description: 'A group of vigilantes sets out to expose and take down corrupt superheroes who abuse their powers.' },
    { title: 'The Lord of the Rings: The Rings of Power', genres: ['fantasy', 'adventure'], country: 'United States', language: 'English', age_rating: 'TV-14', imdb: r5(6.9), rt: rt5(85), year: '2022', director: 'J.D. Payne', actors: ['Morfydd Clark', 'Robert Aramayo'], description: 'Thousands of years before the events of The Lord of the Rings, new legends are forged in the Second Age of Middle-earth.' },
    { title: 'Stranger Things', genres: ['horror', 'science fiction'], country: 'United States', language: 'English', age_rating: 'TV-14', imdb: r5(8.7), rt: rt5(92), year: '2016', director: 'The Duffer Brothers', actors: ['Millie Bobby Brown', 'Finn Wolfhard'], description: 'A boy’s disappearance in a small town uncovers a secret government lab and a monstrous parallel dimension.' },
    { title: 'Game of Thrones', genres: ['fantasy', 'drama'], country: 'United States', language: 'English', age_rating: 'TV-MA', imdb: r5(9.2), rt: rt5(89), year: '2011', director: 'David Benioff', actors: ['Emilia Clarke', 'Kit Harington', 'Peter Dinklage'], description: 'Noble families vie for control of the Iron Throne while an ancient enemy stirs beyond a wall of ice in the north.' },
    { title: 'The Haunting of Hill House', genres: ['horror', 'drama'], country: 'United States', language: 'English', age_rating: 'TV-MA', imdb: r5(8.6), rt: rt5(92), year: '2018', director: 'Mike Flanagan', actors: ['Michiel Huisman', 'Victoria Pedretti'], description: 'Five siblings haunted by their childhood in a notorious house are forced to confront it after a family tragedy.' },
    { title: 'Chucky', genres: ['horror', 'comedy'], country: 'United States', language: 'English', age_rating: 'TV-MA', imdb: r5(7.5), rt: rt5(89), year: '2021', director: 'Don Mancini', actors: ['Zackary Arthur', 'Bjorgvin Arnarson'], description: 'A vintage doll turns up at a yard sale in a quiet suburb, and the killings start almost immediately.' },
    { title: 'The Haunting of Bly Manor', genres: ['horror', 'romance'], country: 'United States', language: 'English', age_rating: 'TV-MA', imdb: r5(7.4), rt: rt5(73), year: '2020', director: 'Mike Flanagan', actors: ['Victoria Pedretti', 'Oliver Jackson-Cohen'], description: 'An au pair hired to look after two orphaned children discovers the estate’s previous caretakers never really left.' },
    { title: 'House of the Dragon', genres: ['fantasy', 'drama'], country: 'United States', language: 'English', age_rating: 'TV-MA', imdb: r5(8.4), rt: rt5(85), year: '2022', director: 'Ryan Condal', actors: ['Emma D’Arcy', 'Matt Smith'], description: 'Two hundred years before Game of Thrones, a war of succession tears the dragon-riding House Targaryen apart.' },
    { title: 'High School Musical: The Musical: The Series', genres: ['musical', 'comedy'], country: 'United States', language: 'English', age_rating: 'TV-G', imdb: r5(6.7), rt: rt5(72), year: '2019', director: 'Tim Federle', actors: ['Joshua Bassett', 'Olivia Rodrigo'], description: 'Students at the real East High stage their own production of the movie that made their school famous.' },
    { title: 'The Mandalorian', genres: ['science fiction', 'adventure'], country: 'United States', language: 'English', age_rating: 'TV-14', imdb: r5(8.7), rt: rt5(93), year: '2019', director: 'Jon Favreau', actors: ['Pedro Pascal', 'Carl Weathers'], description: 'A lone bounty hunter on the outer reaches of the galaxy takes on a job that changes the course of his life.' },
    { title: 'Dark', genres: ['mystery', 'science fiction'], country: 'Germany', language: 'German', age_rating: 'TV-MA', imdb: r5(8.7), rt: rt5(92), year: '2017', director: 'Baran bo Odar', actors: ['Louis Hofmann', 'Karoline Eichhorn'], description: 'The disappearance of a child exposes the double lives and dark secrets of four families across three timelines.' },
    { title: 'The Pacific', genres: ['war', 'drama'], country: 'United States', language: 'English', age_rating: 'TV-MA', imdb: r5(8.3), rt: rt5(88), year: '2010', director: 'Tom Hanks', actors: ['James Badge Dale', 'Joseph Mazzello'], description: 'The Pacific theatre of the Second World War, told through the eyes of three US Marines.' },
    { title: 'Longmire', genres: ['crime', 'western'], country: 'United States', language: 'English', age_rating: 'TV-14', imdb: r5(8.0), rt: rt5(100), year: '2012', director: 'John Coveny', actors: ['Robert Taylor', 'Katee Sackhoff'], description: 'A Wyoming sheriff rebuilding his life after his wife’s death investigates the first murder his county has seen in years.' },
    { title: 'Ted Lasso', genres: ['comedy', 'drama'], country: 'United States', language: 'English', age_rating: 'TV-MA', imdb: r5(8.8), rt: rt5(91), year: '2020', director: 'Bill Lawrence', actors: ['Jason Sudeikis', 'Hannah Waddingham'], description: 'An American college football coach is hired to manage a struggling English Premier League team he knows nothing about.' },
    { title: 'Severance', genres: ['mystery', 'science fiction'], country: 'United States', language: 'English', age_rating: 'TV-MA', imdb: r5(8.7), rt: rt5(97), year: '2022', director: 'Ben Stiller', actors: ['Adam Scott', 'Britt Lower'], description: 'Employees at a mysterious company undergo a procedure that splits their memories between work and home, with unsettling results.' },
    { title: 'Succession', genres: ['drama'], country: 'United States', language: 'English', age_rating: 'TV-MA', imdb: r5(8.9), rt: rt5(96), year: '2018', director: 'Jesse Armstrong', actors: ['Brian Cox', 'Jeremy Strong', 'Sarah Snook'], description: 'The ageing patriarch of a global media empire delays naming a successor, and his children circle like sharks.' },
];

module.exports = { GENRES, MOVIES, SERIES };
