/**
 * Biographical facts for the directors and actors the reseed links into the
 * catalogue, keyed by the exact name used in catalogueData.js. Gender and
 * birth year are well-established public facts about public figures, not
 * private information; birthplace is city-level where confidently known and
 * falls back to country-level rather than inventing a specific city.
 *
 * The seed script throws if a name here doesn't match one used in
 * catalogueData.js (or vice versa) — a silent mismatch would otherwise ship
 * an actor with a missing bio and nobody would notice until a page 500s.
 */

//! g: 'male'|'female' — y: birth year — c: country — p: birthplace (directors only)
const DIRECTORS = {
    'Anthony Russo': { g: 'male', y: 1970, c: 'United States', p: 'Cleveland, Ohio' },
    'Ari Aster': { g: 'male', y: 1986, c: 'United States', p: 'New York City, New York' },
    'Baran bo Odar': { g: 'male', y: 1978, c: 'Switzerland', p: 'Sursee, Switzerland' },
    'Ben Stiller': { g: 'male', y: 1965, c: 'United States', p: 'New York City, New York' },
    'Bill Lawrence': { g: 'male', y: 1968, c: 'United States', p: 'Newington, Connecticut' },
    'Bob Persichetti': { g: 'male', y: 1973, c: 'United States', p: 'New Jersey' },
    'Bong Joon-ho': { g: 'male', y: 1969, c: 'South Korea', p: 'Daegu, South Korea' },
    'Carlo Bernard': { g: 'male', y: 1972, c: 'United States', p: 'United States' },
    'Charlie Brooker': { g: 'male', y: 1971, c: 'United Kingdom', p: 'Reading, England' },
    'Chris Brancato': { g: 'male', y: 1958, c: 'United States', p: 'New York' },
    'Christopher Nolan': { g: 'male', y: 1970, c: 'United Kingdom', p: 'London, England' },
    'Corin Hardy': { g: 'male', y: 1978, c: 'United Kingdom', p: 'Essex, England' },
    'Craig Mazin': { g: 'male', y: 1971, c: 'United States', p: 'Brooklyn, New York' },
    'Damien Chazelle': { g: 'male', y: 1985, c: 'United States', p: 'Providence, Rhode Island' },
    'David Benioff': { g: 'male', y: 1970, c: 'United States', p: 'New York City, New York' },
    'David Fincher': { g: 'male', y: 1962, c: 'United States', p: 'Denver, Colorado' },
    'David Kerr': { g: 'male', y: 1973, c: 'United Kingdom', p: 'United Kingdom' },
    'David Leitch': { g: 'male', y: 1975, c: 'United States', p: 'Genesee, Michigan' },
    'David Simon': { g: 'male', y: 1960, c: 'United States', p: 'Washington, D.C.' },
    'Denis Villeneuve': { g: 'male', y: 1967, c: 'Canada', p: 'Trois-Rivires, Quebec' },
    'Don Mancini': { g: 'male', y: 1963, c: 'United States', p: 'Chicago, Illinois' },
    'Eric Kripke': { g: 'male', y: 1974, c: 'United States', p: 'Toledo, Ohio' },
    'Francis Ford Coppola': { g: 'male', y: 1939, c: 'United States', p: 'Detroit, Michigan' },
    'Frank Darabont': { g: 'male', y: 1959, c: 'France', p: 'Montbliard, France' },
    'George Miller': { g: 'male', y: 1945, c: 'Australia', p: 'Brisbane, Australia' },
    'Hayao Miyazaki': { g: 'male', y: 1941, c: 'Japan', p: 'Tokyo, Japan' },
    'J.D. Payne': { g: 'male', y: 1980, c: 'United States', p: 'United States' },
    'James Cameron': { g: 'male', y: 1954, c: 'Canada', p: 'Kapuskasing, Ontario' },
    'James Wan': { g: 'male', y: 1977, c: 'Malaysia', p: 'Kuching, Malaysia' },
    'Jeb Stuart': { g: 'male', y: 1957, c: 'United States', p: 'Virginia' },
    'Jesse Armstrong': { g: 'male', y: 1970, c: 'United Kingdom', p: 'Shropshire, England' },
    'Joel Coen': { g: 'male', y: 1954, c: 'United States', p: 'Saint Louis Park, Minnesota' },
    'Johan Renck': { g: 'male', y: 1966, c: 'Sweden', p: 'Stockholm, Sweden' },
    'John Coveny': { g: 'male', y: 1968, c: 'United States', p: 'United States' },
    'John Krasinski': { g: 'male', y: 1979, c: 'United States', p: 'Boston, Massachusetts' },
    'John Lasseter': { g: 'male', y: 1957, c: 'United States', p: 'Hollywood, California' },
    'Jon Favreau': { g: 'male', y: 1966, c: 'United States', p: 'Queens, New York' },
    'Jordan Peele': { g: 'male', y: 1979, c: 'United States', p: 'New York City, New York' },
    'Lana Wachowski': { g: 'female', y: 1965, c: 'United States', p: 'Chicago, Illinois' },
    'Lee Unkrich': { g: 'male', y: 1967, c: 'United States', p: 'Cleveland, Ohio' },
    'Marta Kauffman': { g: 'female', y: 1956, c: 'United States', p: 'Philadelphia, Pennsylvania' },
    'Martin Scorsese': { g: 'male', y: 1942, c: 'United States', p: 'New York City, New York' },
    'Matt Owens': { g: 'male', y: 1980, c: 'United States', p: 'United States' },
    'Matt Reeves': { g: 'male', y: 1966, c: 'United States', p: 'New York City, New York' },
    'Matthew Gentile': { g: 'male', y: 1990, c: 'United States', p: 'United States' },
    'Michael Mann': { g: 'male', y: 1943, c: 'United States', p: 'Chicago, Illinois' },
    'Mike Flanagan': { g: 'male', y: 1978, c: 'United States', p: 'Salem, Massachusetts' },
    'Nic Pizzolatto': { g: 'male', y: 1975, c: 'United States', p: 'New Orleans, Louisiana' },
    'Noah Hawley': { g: 'male', y: 1967, c: 'United States', p: 'New York City, New York' },
    'Quentin Tarantino': { g: 'male', y: 1963, c: 'United States', p: 'Knoxville, Tennessee' },
    'Raj Nidimoru': { g: 'male', y: 1975, c: 'India', p: 'Hyderabad, India' },
    'Rian Johnson': { g: 'male', y: 1973, c: 'United States', p: 'Silver Spring, Maryland' },
    'Ridley Scott': { g: 'male', y: 1937, c: 'United Kingdom', p: 'South Shields, England' },
    'Robert Guédiguian': { g: 'male', y: 1953, c: 'France', p: 'Marseille, France' },
    'Robert Zemeckis': { g: 'male', y: 1951, c: 'United States', p: 'Chicago, Illinois' },
    'Ryan Condal': { g: 'male', y: 1981, c: 'United States', p: 'United States' },
    'Sam Mendes': { g: 'male', y: 1965, c: 'United Kingdom', p: 'Reading, England' },
    'Steven Kane': { g: 'male', y: 1968, c: 'United States', p: 'United States' },
    'Steven Knight': { g: 'male', y: 1959, c: 'United Kingdom', p: 'Marlborough, England' },
    'Steven Moffat': { g: 'male', y: 1961, c: 'United Kingdom', p: 'Paisley, Scotland' },
    'Steven Spielberg': { g: 'male', y: 1946, c: 'United States', p: 'Cincinnati, Ohio' },
    'The Duffer Brothers': { g: 'male', y: 1984, c: 'United States', p: 'Durham, North Carolina' },
    'Tim Federle': { g: 'male', y: 1980, c: 'United States', p: 'Pittsburgh, Pennsylvania' },
    'Todd Phillips': { g: 'male', y: 1970, c: 'United States', p: 'Brooklyn, New York' },
    'Tom Hanks': { g: 'male', y: 1956, c: 'United States', p: 'Concord, California' },
    'Vince Gilligan': { g: 'male', y: 1967, c: 'United States', p: 'Richmond, Virginia' },
    'Wes Anderson': { g: 'male', y: 1969, c: 'United States', p: 'Houston, Texas' },
    'Álex Pina': { g: 'male', y: 1967, c: 'Spain', p: 'Madrid, Spain' },
};

const ACTORS = {
    'Aaron Eckhart': { g: 'male', y: 1968, c: 'United States', p: 'Cupertino, California' },
    'Aaron Paul': { g: 'male', y: 1979, c: 'United States', p: 'Emmett, Idaho' },
    'Adam Scott': { g: 'male', y: 1973, c: 'United States', p: 'Santa Cruz, California' },
    'Al Pacino': { g: 'male', y: 1940, c: 'United States', p: 'East Harlem, New York' },
    'Alex Wolff': { g: 'male', y: 1997, c: 'United States', p: 'New York City, New York' },
    'Allison Williams': { g: 'female', y: 1988, c: 'United States', p: 'New Canaan, Connecticut' },
    'Alvaro Morte': { g: 'male', y: 1975, c: 'Spain', p: 'Motril, Spain' },
    'Ana de Armas': { g: 'female', y: 1988, c: 'Cuba', p: 'Havana, Cuba' },
    'Andrew Garfield': { g: 'male', y: 1983, c: 'United States', p: 'Los Angeles, California' },
    'Anne Hathaway': { g: 'female', y: 1982, c: 'United States', p: 'Brooklyn, New York' },
    'Anthony Gonzalez': { g: 'male', y: 2003, c: 'United States', p: 'Downey, California' },
    'Antony Starr': { g: 'male', y: 1975, c: 'New Zealand', p: 'Auckland, New Zealand' },
    'Bella Ramsey': { g: 'female', y: 2003, c: 'United Kingdom', p: 'Nottingham, England' },
    'Benedict Cumberbatch': { g: 'male', y: 1976, c: 'United Kingdom', p: 'London, England' },
    'Billy Bob Thornton': { g: 'male', y: 1955, c: 'United States', p: 'Hot Spring County, Arkansas' },
    'Bjorgvin Arnarson': { g: 'male', y: 2003, c: 'Iceland', p: 'Reykjavik, Iceland' },
    'Bob Odenkirk': { g: 'male', y: 1962, c: 'United States', p: 'Berwyn, Illinois' },
    'Boyd Holbrook': { g: 'male', y: 1981, c: 'United States', p: 'Prestonsburg, Kentucky' },
    'Brad Pitt': { g: 'male', y: 1963, c: 'United States', p: 'Shawnee, Oklahoma' },
    'Brian Cox': { g: 'male', y: 1946, c: 'United Kingdom', p: 'Dundee, Scotland' },
    'Britt Lower': { g: 'female', y: 1984, c: 'United States', p: 'Minnesota' },
    'Bryan Cranston': { g: 'male', y: 1956, c: 'United States', p: 'Hollywood, California' },
    'Bryce Dallas Howard': { g: 'female', y: 1981, c: 'United States', p: 'Los Angeles, California' },
    'Carl Weathers': { g: 'male', y: 1948, c: 'United States', p: 'New Orleans, Louisiana' },
    'Carrie-Anne Moss': { g: 'female', y: 1967, c: 'Canada', p: 'Vancouver, British Columbia' },
    'Charlize Theron': { g: 'female', y: 1975, c: 'South Africa', p: 'Benoni, South Africa' },
    'Cho Yeo-jeong': { g: 'female', y: 1981, c: 'South Korea', p: 'Seoul, South Korea' },
    'Chris Evans': { g: 'male', y: 1981, c: 'United States', p: 'Boston, Massachusetts' },
    'Christian Bale': { g: 'male', y: 1974, c: 'United Kingdom', p: 'Haverfordwest, Wales' },
    'Christoph Waltz': { g: 'male', y: 1956, c: 'Austria', p: 'Vienna, Austria' },
    'Cillian Murphy': { g: 'male', y: 1976, c: 'Ireland', p: 'Douglas, Ireland' },
    'Courteney Cox': { g: 'female', y: 1964, c: 'United States', p: 'Birmingham, Alabama' },
    'Daniel Craig': { g: 'male', y: 1968, c: 'United Kingdom', p: 'Chester, England' },
    'Daniel Kaluuya': { g: 'male', y: 1989, c: 'United Kingdom', p: 'London, England' },
    'Dean-Charles Chapman': { g: 'male', y: 1997, c: 'United Kingdom', p: 'London, England' },
    'Demi Moore': { g: 'female', y: 1962, c: 'United States', p: 'Roswell, New Mexico' },
    'Diego Luna': { g: 'male', y: 1979, c: 'Mexico', p: 'Toluca, Mexico' },
    'Dominic West': { g: 'male', y: 1969, c: 'United Kingdom', p: 'Sheffield, England' },
    'Edward Norton': { g: 'male', y: 1969, c: 'United States', p: 'Boston, Massachusetts' },
    'Elliot Page': { g: 'male', y: 1987, c: 'Canada', p: 'Halifax, Nova Scotia' },
    'Emilia Clarke': { g: 'female', y: 1986, c: 'United Kingdom', p: 'London, England' },
    'Emily Blunt': { g: 'female', y: 1983, c: 'United Kingdom', p: 'London, England' },
    'Emily Rudd': { g: 'female', y: 1993, c: 'United States', p: 'Norwalk, Connecticut' },
    'Emma D’Arcy': { g: 'female', y: 1992, c: 'United Kingdom', p: 'London, England' },
    'Emma Stone': { g: 'female', y: 1988, c: 'United States', p: 'Scottsdale, Arizona' },
    'Finn Wolfhard': { g: 'male', y: 2002, c: 'Canada', p: 'Vancouver, British Columbia' },
    'Frida Gustavsson': { g: 'female', y: 1994, c: 'Sweden', p: 'Stockholm, Sweden' },
    'Gael Garcia Bernal': { g: 'male', y: 1978, c: 'Mexico', p: 'Guadalajara, Mexico' },
    'George MacKay': { g: 'male', y: 1992, c: 'United Kingdom', p: 'London, England' },
    'Hailee Steinfeld': { g: 'female', y: 1996, c: 'United States', p: 'Los Angeles, California' },
    'Hannah Waddingham': { g: 'female', y: 1974, c: 'United Kingdom', p: 'London, England' },
    'Heath Ledger': { g: 'male', y: 1979, c: 'Australia', p: 'Perth, Australia' },
    'Helena Bonham Carter': { g: 'female', y: 1966, c: 'United Kingdom', p: 'London, England' },
    'Idina Menzel': { g: 'female', y: 1971, c: 'United States', p: 'New York City, New York' },
    'Idris Elba': { g: 'male', y: 1972, c: 'United Kingdom', p: 'London, England' },
    'Iñaki Godoy': { g: 'male', y: 2001, c: 'Mexico', p: 'Mexico City, Mexico' },
    'J.K. Simmons': { g: 'male', y: 1955, c: 'United States', p: 'Grosse Pointe, Michigan' },
    'Jack Nicholson': { g: 'male', y: 1937, c: 'United States', p: 'Neptune City, New Jersey' },
    'Jack Quaid': { g: 'male', y: 1992, c: 'United States', p: 'Los Angeles, California' },
    'James Badge Dale': { g: 'male', y: 1978, c: 'United States', p: 'New York City, New York' },
    'Jamie Foxx': { g: 'male', y: 1967, c: 'United States', p: 'Terrell, Texas' },
    'Jared Harris': { g: 'male', y: 1961, c: 'United Kingdom', p: 'London, England' },
    'Jason Sudeikis': { g: 'male', y: 1975, c: 'United States', p: 'Fairfax, Virginia' },
    'Javier Bardem': { g: 'male', y: 1969, c: 'Spain', p: 'Las Palmas, Spain' },
    'Jeff Goldblum': { g: 'male', y: 1952, c: 'United States', p: 'West Homestead, Pennsylvania' },
    'Jennifer Aniston': { g: 'female', y: 1969, c: 'United States', p: 'Sherman Oaks, California' },
    'Jeremy Strong': { g: 'male', y: 1978, c: 'United States', p: 'Boston, Massachusetts' },
    'Jesse Eisenberg': { g: 'male', y: 1983, c: 'United States', p: 'Queens, New York' },
    'Jesse Plemons': { g: 'male', y: 1988, c: 'United States', p: 'Dallas, Texas' },
    'Jessica Chastain': { g: 'female', y: 1977, c: 'United States', p: 'Sacramento, California' },
    'Joaquin Phoenix': { g: 'male', y: 1974, c: 'United States', p: 'San Juan, Puerto Rico' },
    'John Krasinski': { g: 'male', y: 1979, c: 'United States', p: 'Boston, Massachusetts' },
    'John Travolta': { g: 'male', y: 1954, c: 'United States', p: 'Englewood, New Jersey' },
    'Johnny Depp': { g: 'male', y: 1963, c: 'United States', p: 'Owensboro, Kentucky' },
    'Jonas Bloquet': { g: 'male', y: 1990, c: 'Belgium', p: 'Brussels, Belgium' },
    'Joseph Gordon-Levitt': { g: 'male', y: 1981, c: 'United States', p: 'Los Angeles, California' },
    'Joseph Mazzello': { g: 'male', y: 1983, c: 'United States', p: 'Rhinebeck, New York' },
    'Josh Brolin': { g: 'male', y: 1968, c: 'United States', p: 'Los Angeles, California' },
    'Joshua Bassett': { g: 'male', y: 2000, c: 'United States', p: 'Los Angeles, California' },
    'Karl Urban': { g: 'male', y: 1972, c: 'New Zealand', p: 'Wellington, New Zealand' },
    'Karoline Eichhorn': { g: 'female', y: 1965, c: 'Germany', p: 'Berlin, Germany' },
    'Kate Winslet': { g: 'female', y: 1975, c: 'United Kingdom', p: 'Reading, England' },
    'Katee Sackhoff': { g: 'female', y: 1980, c: 'United States', p: 'Portland, Oregon' },
    'Keanu Reeves': { g: 'male', y: 1964, c: 'Canada', p: 'Beirut, Lebanon' },
    'Kit Harington': { g: 'male', y: 1986, c: 'United Kingdom', p: 'Worcester, England' },
    'Laura Dern': { g: 'female', y: 1967, c: 'United States', p: 'Los Angeles, California' },
    'Laurence Fishburne': { g: 'male', y: 1961, c: 'United States', p: 'Augusta, Georgia' },
    'Lee Sun-kyun': { g: 'male', y: 1975, c: 'South Korea', p: 'Seoul, South Korea' },
    'Leonardo DiCaprio': { g: 'male', y: 1974, c: 'United States', p: 'Los Angeles, California' },
    'Louis Hofmann': { g: 'male', y: 1997, c: 'Germany', p: 'Berlin, Germany' },
    'Margot Robbie': { g: 'female', y: 1990, c: 'Australia', p: 'Dalby, Australia' },
    'Marion Cotillard': { g: 'female', y: 1975, c: 'France', p: 'Paris, France' },
    'Marlon Brando': { g: 'male', y: 1924, c: 'United States', p: 'Omaha, Nebraska' },
    'Martin Freeman': { g: 'male', y: 1971, c: 'United Kingdom', p: 'Aldershot, England' },
    'Matt Damon': { g: 'male', y: 1970, c: 'United States', p: 'Boston, Massachusetts' },
    'Matt Smith': { g: 'male', y: 1982, c: 'United Kingdom', p: 'Northampton, England' },
    'Matthew McConaughey': { g: 'male', y: 1969, c: 'United States', p: 'Uvalde, Texas' },
    'Matthew Perry': { g: 'male', y: 1969, c: 'United States', p: 'Williamstown, Massachusetts' },
    'Michael Pena': { g: 'male', y: 1976, c: 'United States', p: 'Chicago, Illinois' },
    'Michiel Huisman': { g: 'male', y: 1981, c: 'Netherlands', p: 'Amstelveen, Netherlands' },
    'Miles Teller': { g: 'male', y: 1987, c: 'United States', p: 'Downingtown, Pennsylvania' },
    'Millie Bobby Brown': { g: 'female', y: 2004, c: 'United Kingdom', p: 'Marbella, Spain' },
    'Miyu Irino': { g: 'male', y: 1988, c: 'Japan', p: 'Tokyo, Japan' },
    'Morena Baccarin': { g: 'female', y: 1979, c: 'Brazil', p: 'Rio de Janeiro, Brazil' },
    'Morfydd Clark': { g: 'female', y: 1989, c: 'United Kingdom', p: 'Sweden' },
    'Morgan Freeman': { g: 'male', y: 1937, c: 'United States', p: 'Memphis, Tennessee' },
    'Olga Kurylenko': { g: 'female', y: 1979, c: 'Ukraine', p: 'Berdiansk, Ukraine' },
    'Oliver Jackson-Cohen': { g: 'male', y: 1986, c: 'United Kingdom', p: 'London, England' },
    'Olivia Rodrigo': { g: 'female', y: 2003, c: 'United States', p: 'Murrieta, California' },
    'Pablo Schreiber': { g: 'male', y: 1978, c: 'Canada', p: 'Toronto, Ontario' },
    'Patrick Wilson': { g: 'male', y: 1973, c: 'United States', p: 'Norfolk, Virginia' },
    'Paul Anderson': { g: 'male', y: 1977, c: 'United Kingdom', p: 'London, England' },
    'Paul Dano': { g: 'male', y: 1984, c: 'United States', p: 'New York City, New York' },
    'Pedro Pascal': { g: 'male', y: 1975, c: 'Chile', p: 'Santiago, Chile' },
    'Peter Dinklage': { g: 'male', y: 1969, c: 'United States', p: 'Morristown, New Jersey' },
    'Ralph Fiennes': { g: 'male', y: 1962, c: 'United Kingdom', p: 'Ipswich, England' },
    'Rebecca Ferguson': { g: 'female', y: 1983, c: 'Sweden', p: 'Stockholm, Sweden' },
    'Rhea Seehorn': { g: 'female', y: 1972, c: 'United States', p: 'Norfolk, Virginia' },
    'Robert Aramayo': { g: 'male', y: 1992, c: 'United Kingdom', p: 'Otley, England' },
    'Robert De Niro': { g: 'male', y: 1943, c: 'United States', p: 'New York City, New York' },
    'Robert Downey Jr.': { g: 'male', y: 1965, c: 'United States', p: 'New York City, New York' },
    'Robert Pattinson': { g: 'male', y: 1986, c: 'United Kingdom', p: 'London, England' },
    'Robert Taylor': { g: 'male', y: 1963, c: 'Australia', p: 'Sydney, Australia' },
    'Robin Wright': { g: 'female', y: 1966, c: 'United States', p: 'Dallas, Texas' },
    'Robinson Stevenin': { g: 'male', y: 1981, c: 'France', p: 'Paris, France' },
    'Rowan Atkinson': { g: 'male', y: 1955, c: 'United Kingdom', p: 'Consett, England' },
    'Rumi Hiiragi': { g: 'female', y: 1987, c: 'Japan', p: 'Tokyo, Japan' },
    'Russell Crowe': { g: 'male', y: 1964, c: 'New Zealand', p: 'Wellington, New Zealand' },
    'Ryan Gosling': { g: 'male', y: 1980, c: 'Canada', p: 'London, Ontario' },
    'Ryan Phillippe': { g: 'male', y: 1974, c: 'United States', p: 'New Castle, Delaware' },
    'Ryan Reynolds': { g: 'male', y: 1976, c: 'Canada', p: 'Vancouver, British Columbia' },
    'Sam Corlett': { g: 'male', y: 1996, c: 'Australia', p: 'Melbourne, Australia' },
    'Sam Neill': { g: 'male', y: 1947, c: 'New Zealand', p: 'Omagh, Northern Ireland' },
    'Samuel L. Jackson': { g: 'male', y: 1948, c: 'United States', p: 'Washington, D.C.' },
    'Sarah Snook': { g: 'female', y: 1987, c: 'Australia', p: 'Adelaide, Australia' },
    'Scarlett Johansson': { g: 'female', y: 1984, c: 'United States', p: 'New York City, New York' },
    'Shahid Kapoor': { g: 'male', y: 1981, c: 'India', p: 'New Delhi, India' },
    'Shameik Moore': { g: 'male', y: 1995, c: 'United States', p: 'Atlanta, Georgia' },
    'Simon Abkarian': { g: 'male', y: 1962, c: 'France', p: 'Beirut, Lebanon' },
    'Song Kang-ho': { g: 'male', y: 1967, c: 'South Korea', p: 'Gimhae, South Korea' },
    'Stellan Skarsgard': { g: 'male', y: 1951, c: 'Sweden', p: 'Gothenburg, Sweden' },
    'Taissa Farmiga': { g: 'female', y: 1994, c: 'United States', p: 'Los Angeles, California' },
    'Tim Allen': { g: 'male', y: 1953, c: 'United States', p: 'Denver, Colorado' },
    'Tim Robbins': { g: 'male', y: 1958, c: 'United States', p: 'West Covina, California' },
    'Timothée Chalamet': { g: 'male', y: 1995, c: 'United States', p: 'New York City, New York' },
    'Tom Hanks': { g: 'male', y: 1956, c: 'United States', p: 'Concord, California' },
    'Tom Hardy': { g: 'male', y: 1977, c: 'United Kingdom', p: 'London, England' },
    'Tom Pelphrey': { g: 'male', y: 1982, c: 'United States', p: 'Howell, New Jersey' },
    'Tommy Lee Jones': { g: 'male', y: 1946, c: 'United States', p: 'San Saba, Texas' },
    'Toni Collette': { g: 'female', y: 1972, c: 'Australia', p: 'Sydney, Australia' },
    'Tony Revolori': { g: 'male', y: 1996, c: 'United States', p: 'Anaheim, California' },
    'Uma Thurman': { g: 'female', y: 1970, c: 'United States', p: 'Boston, Massachusetts' },
    'Ursula Corbero': { g: 'female', y: 1989, c: 'Spain', p: 'Barcelona, Spain' },
    'Vera Farmiga': { g: 'female', y: 1973, c: 'United States', p: 'Clifton, New Jersey' },
    'Victoria Pedretti': { g: 'female', y: 1995, c: 'United States', p: 'Philadelphia, Pennsylvania' },
    'Vijay Sethupathi': { g: 'male', y: 1978, c: 'India', p: 'Chennai, India' },
    'Virginie Ledoyen': { g: 'female', y: 1976, c: 'France', p: 'Aubervilliers, France' },
    'Wagner Moura': { g: 'male', y: 1976, c: 'Brazil', p: 'Salvador, Brazil' },
    'Woody Harrelson': { g: 'male', y: 1961, c: 'United States', p: 'Midland, Texas' },
    'Yerin Ha': { g: 'female', y: 1998, c: 'Australia', p: 'Sydney, Australia' },
    'Zackary Arthur': { g: 'male', y: 2007, c: 'United States', p: 'Los Angeles, California' },
    'Zendaya': { g: 'female', y: 1996, c: 'United States', p: 'Oakland, California' },
    'Zoë Kravitz': { g: 'female', y: 1988, c: 'United States', p: 'Los Angeles, California' },
};

module.exports = { DIRECTORS, ACTORS };
